language: node_js
node_js:
  - "stable"
before_install:
  - npm run install
  - npm run build
after_script:
  - npm run size
  - npm install coveralls
  - coveralls < coverage/lcov.info
cache:
  directories:
    - node_modules
